# Generated by Django 2.2.4 on 2020-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
