# Generated by Django 2.2.4 on 2020-08-22 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordernp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code3', models.CharField(max_length=20)),
                ('start_date3', models.DateTimeField(auto_now_add=True)),
                ('ordered_date3', models.DateTimeField()),
                ('ordered3', models.BooleanField(default=False)),
                ('being_delivered3', models.BooleanField(default=False)),
                ('received3', models.BooleanField(default=False)),
                ('refund_requested3', models.BooleanField(default=False)),
                ('refund_granted3', models.BooleanField(default=False)),
                ('phone3', models.CharField(max_length=220, null=True)),
                ('billing_address3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address3', to='core.BillingAddress')),
                ('coupon3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Coupon')),
                ('items3', models.ManyToManyField(to='core.OrderItem')),
                ('payment3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment')),
                ('shipping_address3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address3', to='core.BillingAddress')),
                ('user3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
