# Generated by Django 2.2.4 on 2020-08-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ordernp'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payafterdelivery',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Ordernp',
        ),
    ]
