# Generated by Django 2.2.4 on 2020-08-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200822_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payafter',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
