# Generated by Django 2.2.4 on 2020-10-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
