# Generated by Django 2.2.4 on 2020-10-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
