# Generated by Django 2.2.4 on 2020-10-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_producthit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthit',
            name='items',
        ),
        migrations.AddField(
            model_name='producthit',
            name='items',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
