# Generated by Django 2.2.4 on 2020-10-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201027_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='item',
            name='votes_total',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
